import Head from "next/head";
import Accordion from "../components/Accordion";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Responsive Accordion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Accordion />
    </div>
  );
}
